services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass
      POSTGRES_DB: gamedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg2://gameuser:gamepass@db:5432/gamedb
      REDIS_URL: redis://redis:6379/0
      OLLAMA_URL: http://ollama:11434
    depends_on:
      - db
      - redis
      - ollama
    ports:
      - "8000:8000"
    develop:
      watch:
        # quand un fichier Python change → sync dans le conteneur
        - path: ./backend
          target: /app
          action: sync
        # si le pyproject.toml change → rebuild complet
        - path: ./backend/pyproject.toml
          action: rebuild
        - path: ./backend/poetry.lock
          action: rebuild

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    develop:
      watch:
        # sync direct du code source frontend
        - path: ./frontend
          target: /app
          action: sync
        # si package.json change → rebuild complet
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild

  ollama:
    image: ollama/ollama:latest
    restart: always
    volumes:
      - ./ia/ollama:/root/.ollama
      - ./ia/ollama-entrypoint.sh:/entrypoint.sh
    ports:
      - "11434:11434"
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    # Uncomment the following lines to enable GPU support with NVIDIA Docker
    # Make sure you have the NVIDIA Container Toolkit installed on your host machine
    # and that your GPU is compatible.
    # Also, ensure that the base image supports CUDA if needed.
    # For more details, refer to the NVIDIA documentation:
    # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [ gpu ]

volumes:
  pgdata:
  ollama_data:
